#!/bin/sh
exec >>log 2>&1

URL=Course
URL=Geo

ab -n10000 -c100 http://localhost:3000/$URL
ab -n10000 -c100 http://localhost:3000/$URL
ab -n10000 -c100 http://localhost:3000/$URL
ab -n10000 -c100 http://localhost:3000/$URL
ab -n10000 -c100 http://localhost:3000/$URL
