#!/bin/sh

#
# specify dependencies as a list of {dir|file}:{symlink|spec} lines
# spec := COPY -- copy file; BUNDLE -- append file to a bundle
#
deps='
creationix/stack/stack.js:stack.js
christkv/node-mongodb-native:mongodb
dvv/underscore/underscore.js:underscore.js
#dvv/stack.static/src/index.coffee:stack.static.coffee
creationix/simple-mime/simple-mime.js:simple-mime.js
dvv/simple-geoip/lib:simple-geoip
3rd-Eden/node-useragent/useragent.js:useragent.js
tautologistics/node-htmlparser/lib/htmlparser.js:htmlparser.js
#LearnBoost/Socket.IO-node:io
stephank/Socket.IO-node:io
'

#
# DO NOT CHANGE AFTER THIS LINE
#

#
# download dependencies
#
lib=node_modules
COPY=public/js
BUNDLE=public/js/bundle.js
mkdir -p "$lib"
rm -f "$BUNDLE"
for dep in $deps; do
	# skip comments
	case "$dep" in
		\#*) continue ;;
	esac
	# parse definition
	path=${dep%:*}
	link=${dep##*:}
	author=${path%%/*}
	path=${path#*/}
	git=${path%%/*}
	# fetch the package
	echo -n "package ${author}'s $git: "
	#continue
	if ! test -d git/${git}; then
		#git clone https://github.com/${author}/${git}.git git/${git}
		mkdir -p git/${git}
		wget -ct3 -q --progress=bar --no-check-certificate http://nodeload.github.com/${author}/${git}/tarball/master -O- | tar -xzf- --strip 1 -C git/${git}
		cd git/${git}
		#if test -f Makefile; then
		#	make
		#fi
		if test -f wscript; then
			node-waf distclean configure build
		fi
		cd ../..
	fi
	# symlink entry point
	if test "Q$link" = 'QBUNDLE'; then
		echo "$path bundled into $BUNDLE"
		cat "git/$path" >> "$BUNDLE"
	elif test "Q$link" = 'QCOPY'; then
		echo "$path copied to $COPY"
		cp "git/$path" "$COPY"
	elif test "Q$link" != 'Q'; then
		echo "$path symlinked to $lib/$link"
		test -e "$lib/$link" || ln -s "../git/$path" "$lib/$link"
	fi
done

#
# compile coffee
#
coffee -bc -o lib src/*

#
# minify client-side stuff
#
#jsmin "$BUNDLE"
